# fly.toml app configuration file generated for shooter on 2023-06-20T01:25:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shooter"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builtin = "node"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
